version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r backend/requirements.txt -t backend/
  build:
    commands:
      - cd backend
      - zip -r ../function.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name CICD --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
