version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r backend/requirements.txt -t .
  build:
    commands:
      - echo Zipping the Lambda function...
      - zip -r function.zip . -x "*.git*" "*__pycache__*"
  post_build:
    commands:
      - echo Deploying to AWS Lambda...
      - aws lambda update-function-code --function-name CICD --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
