phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r function.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name FeedbackHandler --zip-file fileb://function.zip
